import type { Metadata } from "next";
import "./globals.css";
import { Inter, Fira_Mono } from "next/font/google";
import Navbar from "@/components/Navbar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const firaMono = Fira_Mono({
  variable: "--font-fira-mono",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "AIポートフォリオアプリ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja" className={`${inter.variable} ${firaMono.variable}`}>
      <body className="antialiased">
        <Navbar />
        <main className="p-4">{children}</main>
      </body>
    </html>
  );
}
